### ISSUE TITLE
✨ feat: Header UI

### ISSUE THREAD

**Issue by euncherry** [Kakaotech-18-Ecommerce/Kakaotech-18-Front-end#9]
# Title

- Header UI 구성 및 개발 

# TODO
### UI
- [x] ref를 통해서 bg-color 변경
- [x] ref를 통해서 검색창 적용
- [x] category 구현
- [ ] Header 반응형 구현

### Features
- [ ] Role에 따른 구성 구현
- [ ] 검색 기능 구현

### Layers
- [ ] 최적화 구현
- [ ] 폴더 구조 정리
